---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "k8s-node"
  namespace: "default"
  labels:
    app: "k8s-node"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "k8s-node"
  template:
    metadata:
      labels:
        app: "k8s-node"
    spec:
      containers:
        - name: "k8s-hello-node"
          imagePullPolicy: Always
          image: "libinmathew/stunning-broccoli-nodejs-app:prod"
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "700m"

---


apiVersion: "v1"
kind: "Service"
metadata:
  name: "k8s-node-service"
  namespace: "default"
  labels:
    app: "k8s-node"
spec:
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 3000
  selector:
    app: "k8s-node"
  type: "LoadBalancer"